#!/bin/sh

source $(dirname $0)/_common

stop_if_not_get

delay=$(tc qdisc ls dev eth0 | grep -v default |cut -d " " -f 9)

echo "Content-Type: text/plain"
echo

if [ "$delay" = "100.0ms" ]; then
  echo "3g"
elif [ "$delay" = "440.0ms" ]; then
  echo "edge"
elif [ "$delay" = "600.0ms" ]; then
  echo "very_bad"
elif [ "$delay" = "5.0ms" ]; then
  echo "dsl"
elif [ "$delay" = "200.0ms" ]; then
  echo "bad"
elif [ "$delay" = "900.0ms" ]; then
  echo "14.4"
elif [ "$delay" = "700.0ms" ]; then
  echo "56"
elif [ "$delay" = "1.5s" ]; then
  echo "ppp_oss"
elif [ "$delay" = "500.0ms" ]; then
  echo "vsat"
else
  echo "none"
fi

